[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Tim Schuster <mail@timschuster.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.9"
regex = "1.4.2"

[features]
default = ["aoc2021"]
aoc2020 = []
aoc2021 = []