[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Tim Schuster <mail@timschuster.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.9"
regex = "1.4.2"
chrono = "0.4.19"
bit-vec = "0.6.3"
log = "0.4.14"
env_logger = "0.9.0"

[features]
default = ["aoc2021"]
aoc2020 = []
aoc2021 = []

[profile.release]
opt-level = 3
debug = false
rpath = false